defaults:
  - _self_

data_config: 'config/input_data.yaml'

training:
  learning_rate: 1.0e-5
  wave_speed: 2.5
  boundary_condition:
    steps: 500000
    sample_size: 500
  physics_informed:
    enabled: true
    sample_size: 500
    steps: 5000
    max_training_time: 0.2
    loss_balance: 0.00001
  optimizer:
    type: 'adam'
    loss: 'mse'
    metrics: null
  checkpointing:
    save: true
    save_dir: './save_pinn_sine/'
    load: false
    load_dir: './save_pinn_sine/'
  logging:
    log_dir: './logs/'
    save_frequency: 100
    checkpoint_frequency: 100

model:
  input_dim: 3
  n_layers: 10
  n_units: 1024
  output_dim: 1
  output_activation: 'linear'
  activation: 'sine'
  kernel_initializer: null
